name: tela_treino
description: "Tela de apoio a treino profissional"
publish_to: 'none'

version: 2.0.0+13

environment:
  sdk: '>=3.11.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.1

  # Interface e Funcionalidades
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  pip_view: ^0.9.7
  vibration: ^2.0.1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  url_launcher: ^6.3.0

  # Gráficos e Sons
  fl_chart: ^0.66.0
  flutter_ringtone_player: ^4.0.0+4
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
